### ISSUE TITLE
Why isn't there a Linux version?

### ISSUE THREAD

**Issue by sikenali** [davidhu2000/youtube_desktop#107]
Why isn't there a Linux version?

**Comment by davidhu2000** [comment]
@jingle0927 we were trying to limit the scope initially. We didn't know what we were doing, but it seems like adding a linux version do not add too much additional work, once we complete, we will be sure to add it. Just that no one really had time lately to work this. 😞

**Comment by alekksander** [comment]
+1

**Comment by alekksander** [comment]
+1

**Comment by insign** [comment]
hell man, we are people too. Just ask for help, the most popular OS for dev, need to suffer with this....

**Comment by tilda** [comment]
The app can be built easily using the package.json scripts (`npm run dist`, `npm run build`, etc)

**Comment by davidhu2000** [comment]
Looks like there will be linux version. `electron-builder` to the rescue.

**Comment by tilda** [comment]
Sorry for bumping a sorta old issue, but is there any update on this?

**Comment by eriknyk** [comment]
there is a more simple app https://github.com/eriknyk/youtb
it is not made by hand it is only a desktop wrapper for the original youtube web sources and works fine on linux, it already has the .tar.gz package of the app in the download section. Regards.
