### ISSUE TITLE
Player page needs more sections

### ISSUE THREAD

**Issue by davidhu2000** [davidhu2000/youtube_desktop#37]
We are missing a section in the video details page. We don't have the section with video title. This is what actual youtube look like.

<img width="861" alt="screen shot 2017-04-11 at 10 39 21 am" src="https://cloud.githubusercontent.com/assets/15827041/24922463/3d263ea4-1ea3-11e7-9255-e2ef37dae94d.png">

This is what ours look like 

<img width="704" alt="screen shot 2017-04-11 at 10 43 31 am" src="https://cloud.githubusercontent.com/assets/15827041/24922598/bf32e92e-1ea3-11e7-805a-7df3632a6143.png">

**Comment by davidhu2000** [comment]
You can continue to work from the `player-frame` branch, just make sure to `git pull` on the master branch, then `git rebase master` while on the `player-frame` branch.

**Comment by cjudge1337** [comment]
I've got everything in that section now, except the number of subscribers next to the subscribe button. That would require a separate API call to pull, so if you think it's worth it I can set that up too. Otherwise it's good to have Alex work on it.

**Comment by davidhu2000** [comment]
Pretty sure that extra api call doesn't cost too much, let's add it in. 

Are you working on `player-frame` branch still?

**Comment by cjudge1337** [comment]
Sounds good, and yes.
